from fastapi import FastAPI
from fastapi.responses import JSONResponse
from fastapi.openapi.utils import get_openapi

from app.config.routers import ROUTERS

app = FastAPI(
    title="Portal de juegos",
    description="API con arquitectura en capas",
    version="1.0.0",
)

for router in ROUTERS:
    app.include_router(router)


@app.get("/")
async def root():
    return {"message": "API funcionando correctamente"}


@app.get("/health")
async def health_check():
    return JSONResponse(status_code=200, content={"status": "healthy"})


def custom_openapi():
    if app.openapi_schema:
        return app.openapi_schema
    openapi_schema = get_openapi(
        title=app.title,
        version=app.version,
        description=app.description,
        routes=app.routes,
    )
    # Ensure BearerAuth exists if not autogenerated
    openapi_schema.setdefault("components", {}).setdefault("securitySchemes", {})
    openapi_schema["components"]["securitySchemes"].setdefault(
        "BearerAuth",
        {"type": "http", "scheme": "bearer", "bearerFormat": "JWT"},
    )
    openapi_schema.setdefault("security", [{"BearerAuth": []}])
    app.openapi_schema = openapi_schema
    return app.openapi_schema


app.openapi = custom_openapi
